server:
  port: 9015

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: client
        uri: http://localhost:9010/client/
        predicates:
        - Path=/client/**
        # =====================================
      - id: provider
        uri: http://localhost:9011/provider/
        predicates:
        - Path=/provider/**
        # =====================================

  application:
    name: gateway
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway


